### ISSUE TITLE
schema property doesn't work with e2e tests using supertest

### ISSUE THREAD

**Issue by zulfiqarjunejo** [egomobile/node-http-server#12] opened 2021-11-23 12:04 UTC
Hi,

I am writing this here to keep a record for our team that schema property does not work well with supertest. A workaround that we have found is to use `validate(<YOUR_SCHEMA>)` as a middleware.

We will fix this soon.

Regards,
Zulfiqar Ahmed

**Comment by mkloubertego** [comment] 2021-12-10 09:12
i currently cannot reproduce this locally ... i will check this in our projects

**Comment by mkloubertego** [comment] 2021-12-13 17:58
@zulfiqarjunejo 

You must be careful, when using middlewares, like [body-parser](https://www.npmjs.com/package/body-parser).

This is a middleware, that only works with [Express](https://www.npmjs.com/package/express) and is no generic middleware like [cors](https://www.npmjs.com/package/cors), which runs with the module.

Why this does not work with `body-parser` is simple: The middleware expects methods or properties, which do not exist in out request interface, only in an Express request object.

So something like a "null reference" is throw, which is not caught, what means that server is not able to do a `response.end()`, what you will see that way, that the connection would hang up.

Most of the middlewares in the Express ecosystem do work with the module, but `body-parser` is special, because it is a middleware created by the people of Express for the Express module.

**Comment by zulfiqarjunejo** [comment] 2021-12-15 10:52
@mkloubert I understand that. However, this problem was even there before `body-parser`.

**Comment by mkloubertego** [comment] 2021-12-15 10:56
You are right ... the problem is not the body parser, it is a small issue between Jest and the module.

the `app.controllers()` can only be called once, otherwise it would register the middlewares again and again

of course Jest does not execute a test in a own processes ... it executes all tests in one process

**Comment by mkloubertego** [comment] 2022-12-29 17:26
this is fixed in the code

**Closed by mkloubertego** 2022-12-29 17:26 UTC
Labels: bug
